name: "Verifly"
description: "Fast CI for Lean proof verification with mathlib caching"

runs:
  using: "composite"
  steps:
    - name: Install Lean toolchain (elan)
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf \
          | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash

    - name: Lake update
      run: lake update
      shell: bash

    - name: Fetch mathlib precompiled cache
      run: |
        lake exe cache get || echo "⚠️ No mathlib cache available"
      shell: bash

    - name: Verify proofs (lake build)
      run: |
        set -o pipefail
        lake build 2>&1 | tee verifly.log
      shell: bash

    - name: Failure summary
      if: failure()
      run: |
        echo "❌ Verifly: Lean verification failed"
        echo "------ Last 40 lines ------"
        tail -n 40 verifly.log
        echo "---------------------------"
      shell: bash

